# 排除的dex program ids，如果不想被交易，可以在这里配置上
jup_exclude_dex_program_ids:
  - "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
  - "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG"
#jupiter的本地端口
jupiter_local_port: 18080
#是否禁用本地jupiter
jupiter_disable_local: false
#是否使用本地缓存，建议禁用
jupiter_use_local_cache: false
#jupiter的market模式，建议选择remote
jupiter_market_mode: "remote"

#自动重启时间，设置为0不会重启，单位为分钟
auto_restart: 60
#________________以上为jup相关配置内容_______________
# 是否禁用本地bot启动
disable_local_bot: false
# grpc token，如果你得gprc有token验证，可以在这里配置上
yellowstone_grpc_token: ""
# 从birdeye api 加载代币，最大加载50个代币,需要自己配置key，可以去注册一个账号key免费https://bds.birdeye.so/
#load_mints_from_birdeye_api_max_mints: 0
#birdeye_api_key: "xxxxxx"

#jito配置UUID，没怎么测试，建议先不要用,使用多ip的方法，而不是配置uuid
#jito_uuid: ""
#从url加载代币，可以从你的jup加载代币，你的jup加载了什么币，会拉到bot内。如果从其他地方拉取，需要和jup返回结构抱持一致，建议从jup加载代币
#load_mints_from_url: "https://rustmevtokens.itssx.com/api/arbitrage-tokens"
#从文件加载代币
#intermediate_tokens_file: "./123.json"
#从配置文件加载代币
intermediate_tokens:
  - "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
  - "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
  - "MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5"
  - "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"
  - "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv"
  - "27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4"
  - "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump"
  - "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr"
  - "zBTCug3er3tLyffELcvDNrKkCymbPWysGcWihESYfLg"
  - "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"
  - "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux"


  # 排除的币种
not_support_tokens:
#最大代币数量
max_tokens_limit: 30
#最小利润阈值
min_profit_threshold: 100
#最大tip限制，单位lamports，给jito的最大限制
max_tip_lamports: 600000000
#静态tip百分比，给jito的tip百分比
static_tip_percentage: 0.75


#建议先从小的开始0.1-1s，不要设置太多，影响性能
trade_range:
  - 0.1
  - 0.2
  - 0.5
  - 3
trade_range_strategy:
  enable_strategy: true
  ranges:
    - from: 0.1    # 
      to: 1     # 
      step: 0.11
      size: 5      # 
    - from: 1    # 
      to: 10     # 
      step: 0.6
      size: 10      # 
    - from: 10    # 
      to: 60     # 
      step: 9.3
      size: 5      # 



#发送交易类型，建议选择Mixed，可选Rpc,Grpc,Mixed，选择Mixed可以让你的ip限制速率翻倍
rpc_type: Mixed
#blockhash rpc类型，建议选择Rpc，可选Grpc,Rpc，当前实现Grpc不是订阅的，等改成订阅的再选用Grpc
blockhash_rpc_type: Grpc

#是否开启block缓存，建议开启
blockhash_cache_enabled: true
#block缓存过期时间，单位ms，缓存1s没啥问题，降低下节点压力
blockhash_cache_ttl_ms: 1000

#日志相关能力
log_rate_limit: false
#打印机会
log_opportunities: false
#打印交易执行
log_trade_execution: false
#是否开启单独钱包
enable_separate_wallet: true
#生成的随机钱包个数
separate_wallet_size: 3000

#jup 调优
#是否只使用单跳
only_direct_routes: false
#限制中间代币为顶级代币，建议开启，此参数也就是在多跳的时候有用，现在多跳没那么好使，先这样
restrict_intermediate_tokens: true
#是否预检交易大小，先暂时关闭，这个只对多跳有用，等待后续开发
check_transaction_size: false
#是否开启动态计算预算,建议开启
dynamic_compute_unit_limit: true
#计算预算百分比，设置这个值是因为，模拟后的cu可能偏大，可以设置百分比二次修改cu限制，近一步降低cu限制
cu_limit_percentage: 1.0
#是否开启kamino借贷
enable_kamino: true
single_swap_compute_unit_limit: 90000
# 您为闪电贷款设置的计算预算，单位为cu，默认10w,如果当前交易有闪电贷，那么会自动加上预算
loan_compute_unit_limit: 110000



blind_trade_config:
  #是否开启盲发
  enabled: true
  #是否开启quote，如果开启,如果开启quote，还是会根据quote结果进行修改结果，如果不开启，那么直接随机组合AMM进行交易
  enable_quote: true
  blind_type: RandomFixed #可选值：Fixed,RandomFixed,Percent,固定值、随机固定值、交易额百分比
  # 1、盲法利润固定值，无论多大的交易额，都根据此利润值来模拟quote到的利润
  expect_min_profit_threshold: 0.0001 #单位为sol
  # 2、随机固定利润值，单位为sol
  random_fixed_profit: #单位为sol
    - 0.000012
    - 0.00002
    - 0.0001    
    - 0.0002
    - 0.0003
    - 0.0009
    - 0.001
    - 0.01
    - 0.1
  # 2、（不进行quote）盲发预期利润百分比,预期利润百分比开启后，固定blind_expect_min_profit_threshold 将失效，按照交易额度来控制给jito的小费比率，也就是
  #毛利润 = 交易额 *(1+blind_expect_profit_percent)
  #jito 小费 = 毛利 * static_tip_percentage，建议保守和冲刺都要有，找机会
  blind_expect_profit_percent:
    - 0.00002 # 保守策略: 交易100 SOL，预期利润0.002 SOL (≈$0.14) => 约 $2.60
    - 0.00005 # 保守策略: 交易100 SOL，预期利润0.005 SOL (≈$0.35) => 约 $6.50


#是否开启随机引擎，建议开启，随机引擎会随机选择一个节点进行交易，这样的你的QPS会有提升
random_engine: false

#交易memo，可以不设置
memo: "1"

#jupiter的webserver线程数
jupiter_webserver: 4
#jup的更新线程数
jupiter_update: 4
#jupiter的总线程数
total_thread_count: 16


#你的私钥数组，系统启动后会在当前目录下生成一个PRIVATEKEY文件，里面是加密后的私钥，虽然做了加密，但是还是要小心，不要泄露，系统启动后会将此项配置删除，不在服务器上储存私钥
private_key: ""
#Solana RPC 节点地址。
rpc_url: "http://5.39.222.42:8899"
yellowstone_grpc_url: "http://5.39.222.42:10001"
jupiter_api_url: "http://127.0.0.1:18080"
# Jito MEV-Block-Engine 节点配置列表，建议配置上多个节点，随机选择一个节点进行交易，这样的你的QPS会有提升，尽量选择几个距离你比较近的节点，当然全发也可以，目测日本较慢，会降低整体效率,如果想追求速度，那么jito的引擎只开本区域，你会起飞
jito_engine:
- "http://5.39.222.42:8081" 
- "http://146.0.74.190:8081" 
- "http://31.207.46.17:8081" 
- "http://5.39.218.113:8081" 

#性能相关，开启多少个线程,系统负载全靠这个控制
thread_count: 16
#每个线程里多少个网络IO，可以一个线程配2个左右，具体看性能，自行调试，作者也不知道多少是好的
max_concurrent: 2

