server:
  host: "45.155.102.8" #服务绑定的ip，如果需要外网访问请填写0.0.0.0
  port: 8081 # 服务在哪个端口启动
  workers: 200 # web线程数
  keep_alive_timeout: 75 # 秒为单位，外部链接保持多久长链接
  shutdown_timeout: 30 # 秒为单位，关闭的时候等待多少秒让所有的进程完成

logging:
  level: "info"
  format: "json"
  access_log: false # 是否打印访问日志，可以根据这个查看延时
  access_success_rate: true # 是否打印成功率


# 异步发送配置，如果你的proxy 链接的engine 距离你的bot太远，你可以选择异步模式，bot只负责提交交易到proxy，具体怎么发送，由proxy来慢慢消费
async_sender:
  enabled: true # 是否启用异步发送
  workers: 300 # 线程池大小
  queue_size: 1000 # 任务队列大小


# jito 发送引擎配置信息,你可以起多个proxy，每个proxy指定不同的区域
jito_engine:
   - NL  # 荷兰
   - DE 
   - NY 
   - SLC 
   - Tokyo
   - LND 
   - Main 

# 发送交易类型，建议选择Mixed，可选Rpc,Grpc,Mixed
rpc_type: Mixed
# jito uuid
jito_uuid: ""
# 多ip配置，如果不想写可以将ip_addr注释掉，然后系统会自动扫描网卡
#ip_addrs: []

# 校验权限，如果鉴权不通过那么，程序会自动停止。请通过正规渠道购买，代理请求会进行采样，只允许支付钱包发送的请求被代理，否则程序会自动停止
auth_config:
  pay_wallet_address: "4QU7nS3EkRb9wAMY2dajhGr44UKvRYVspZjfQdko2Li5"
  signature: "4Z8t3x2bKxJaYAHkSoUeJ9XNjiuNBX6ahr2kxhoba4bANRZydzXbKPT9kt5bSZMPGvLBjtzpoUg7NGtH87pudRZa"
